---

- name: Install Nginx
  package:
    name: nginx
    state: latest

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy web page
  copy:
    src: index.html
    dest: /var/www/html
